"""followers

Revision ID: 18baf30a2d58
Revises: a281509bfed9
Create Date: 2019-08-16 21:09:54.782416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18baf30a2d58'
down_revision = 'a281509bfed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
