"""add language to post

Revision ID: 50500258f71e
Revises: 18baf30a2d58
Create Date: 2019-08-22 14:39:12.025304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50500258f71e'
down_revision = '18baf30a2d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
